import { Nunito } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar/Navbar'
import ClientOnly from './components/ClientOnly'
import RegisterModal from './components/Modals/RegisterModal';
const inter = Nunito({ subsets: ['latin'] })
Navbar
export const metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
  Image: '/vercel.svg',
}
const font = Nunito({
  subsets: ['latin'],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>

        <ClientOnly>
          <RegisterModal />
          <Navbar />
        </ClientOnly> 
        {children}</body>
    </html>
  )
}
